import React, { useEffect, useRef, useState } from 'react';
import { Hammer, Check, Loader2, Terminal, Smartphone } from 'lucide-react';

const STEPS = ['Understanding your idea…', 'Designing the data model…', 'Generating the interface…', 'Wiring the AI logic…', 'Deploying preview…'];
const SUGGESTIONS = ['A booking app for my barbershop in Arabic & English', 'A dashboard that tracks my store\'s daily sales', 'A landing page for my agency with a lead form'];

const IbniDemo: React.FC = () => {
  const [prompt, setPrompt] = useState('');
  const [phase, setPhase] = useState<'idle' | 'building' | 'done'>('idle');
  const [step, setStep] = useState(0);
  const timer = useRef<ReturnType<typeof setInterval> | null>(null);

  const build = (text?: string) => {
    const p = (text ?? prompt).trim();
    if (!p || phase === 'building') return;
    setPrompt(p); setPhase('building'); setStep(0);
    timer.current = setInterval(() => {
      setStep((s) => {
        if (s >= STEPS.length - 1) { if (timer.current) clearInterval(timer.current); setTimeout(() => setPhase('done'), 500); return s; }
        return s + 1;
      });
    }, 850);
  };

  useEffect(() => () => { if (timer.current) clearInterval(timer.current); }, []);

  return (
    <div className="w-full h-full grid md:grid-cols-2 text-[#e8ecf4]" style={{ background: '#0a0e17' }}>
      <div className="p-5 border-b md:border-b-0 md:border-r" style={{ borderColor: 'rgba(255,255,255,0.08)', background: '#0d1220' }}>
        <label className="text-[10px] font-bold uppercase tracking-[0.2em] text-[#5b6478]">What should IBNI build?</label>
        <textarea value={prompt} onChange={(e) => setPrompt(e.target.value)}
          placeholder="e.g. A booking app for my barbershop…" rows={2}
          className="mt-2 w-full rounded-xl p-3.5 text-sm resize-none focus:outline-none"
          style={{ background: '#111726', border: '1px solid rgba(255,255,255,0.08)', color: '#e8ecf4' }} />
        <button onClick={() => build()} disabled={phase === 'building' || !prompt.trim()}
          className="btn-primary mt-2.5 w-full py-2.5 rounded-lg font-semibold text-sm disabled:opacity-40 flex items-center justify-center gap-2">
          {phase === 'building' ? <><Loader2 size={15} className="animate-spin" /> Building…</> : <>⚡ Build my app</>}
        </button>
        <div className="mt-3 flex flex-wrap gap-2">
          {SUGGESTIONS.map((s) => (
            <button key={s} onClick={() => build(s)} className="text-[11px] px-2.5 py-1.5 rounded-full text-[#8b93a7] hover:text-white transition-colors text-left"
              style={{ background: '#111726', border: '1px solid rgba(255,255,255,0.08)' }}>{s}</button>
          ))}
        </div>
        {phase !== 'idle' && (
          <div className="mt-4 rounded-xl p-3.5 font-mono text-xs space-y-2" style={{ background: '#05070d', border: '1px solid rgba(255,255,255,0.06)' }}>
            <p className="text-[#5b6478] flex items-center gap-2"><Terminal size={12} /> ibni build</p>
            {STEPS.map((s, i) => (
              <p key={s} className={`flex items-center gap-2 transition-opacity duration-300 ${i <= step ? 'opacity-100' : 'opacity-0'}`}>
                {i < step || phase === 'done' ? <Check size={12} className="text-emerald-400" /> : <Loader2 size={12} className="text-[#8b93a7] animate-spin" />}
                <span className={i < step || phase === 'done' ? 'text-emerald-400' : 'text-[#c7cede]'}>{s}</span>
              </p>
            ))}
            {phase === 'done' && <p className="text-emerald-400 font-bold pt-1">✓ Preview ready in 4.3s</p>}
          </div>
        )}
      </div>
      <div className="p-5 flex items-center justify-center min-h-[300px]" style={{ background: '#080b12' }}>
        {phase === 'done' ? (
          <div className="w-full max-w-[230px] rounded-[1.8rem] overflow-hidden reveal" style={{ border: '5px solid #1b2233', boxShadow: '0 0 40px -8px rgba(16,185,129,0.4)' }}>
            <div className="px-4 py-3.5 text-white" style={{ background: 'linear-gradient(120deg,#059669,#10b981)' }}>
              <p className="text-[10px] opacity-80">Generated by IBNI</p>
              <p className="font-bold text-sm leading-tight mt-0.5 line-clamp-2">{prompt}</p>
            </div>
            <div className="p-3.5 space-y-2.5" style={{ background: '#0d1220' }}>
              {[92, 68, 80].map((w, i) => (
                <div key={i} className="rounded-lg p-2.5" style={{ border: '1px solid rgba(255,255,255,0.08)' }}>
                  <div className="h-2 rounded mb-2" style={{ width: `${w}%`, background: 'rgba(16,185,129,0.4)' }} />
                  <div className="h-2 rounded" style={{ width: `${w - 25}%`, background: 'rgba(255,255,255,0.08)' }} />
                </div>
              ))}
              <div className="rounded-lg text-white text-center text-xs font-semibold py-2.5" style={{ background: '#10b981' }}>احجز الآن · Book now</div>
            </div>
          </div>
        ) : (
          <div className="text-center text-[#5b6478]">
            <Smartphone size={38} className="mx-auto mb-3 opacity-50" />
            <p className="text-sm">Your app preview appears here.</p>
            <p className="text-xs mt-1 opacity-70">Type an idea and hit “Build my app”.</p>
          </div>
        )}
      </div>
    </div>
  );
};

export default IbniDemo;
