import React from 'react';
import LegalPageShell from './LegalPageShell';

const PrivacyPolicy: React.FC = () => (
  <LegalPageShell
    title="Privacy Policy"
    updated="July 2026"
    path="/privacy"
    seoDescription="How MB AI Group collects, uses, and protects information across mbai-group.com and its products."
  >
    <section>
      <h2>Who this covers</h2>
      <p>
        This policy covers <strong>mbai-group.com</strong> and the ventures embedded on it (AutoLeadss, Virlo Studio,
        IBNI, TUT, and the demo pages under this domain). It's operated by Mohanad Barakat, trading as MB AI Group /
        MBAI Solutions, based in Cairo, Egypt and Dubai, UAE.
      </p>
    </section>

    <section>
      <h2>What we collect</h2>
      <ul>
        <li><strong>Contact &amp; booking details you give us directly</strong> — name, email, phone/WhatsApp, and company, when you use the Contact section, book a call via Calendly, or message us on WhatsApp/email.</li>
        <li><strong>Testimonial submissions</strong> — the headline, quote, name, role, and company you enter in the "Share Your Result" form, if you choose to submit one.</li>
        <li><strong>Basic hosting logs</strong> — standard server/request logs generated by our hosting provider (Vercel) for security and reliability, not tied to a marketing profile.</li>
      </ul>
      <p>We do not currently run third-party analytics or advertising trackers on this site.</p>
    </section>

    <section>
      <h2>Third-party services</h2>
      <p>
        Booking a call embeds <strong>Calendly</strong>, which operates under its own privacy policy. Testimonial and
        contact-form data (once storage is fully configured) is processed by our hosting provider, <strong>Vercel</strong>,
        and — where applicable — a Postgres database provider.
      </p>
    </section>

    <section>
      <h2>How we use it</h2>
      <ul>
        <li>To respond to your enquiry or booking request.</li>
        <li>To review and, with your permission, publish submitted testimonials.</li>
        <li>To keep the site secure and working correctly.</li>
      </ul>
      <p>We don't sell personal information, and we don't share it with third parties for their own marketing.</p>
    </section>

    <section>
      <h2>Your choices</h2>
      <p>
        Email <strong>mohanad.barakat@mbai-group.com</strong> at any time to ask what we hold about you, request a
        correction, or ask us to delete it — including a previously submitted testimonial.
      </p>
    </section>
  </LegalPageShell>
);

export default PrivacyPolicy;
